[package]
name = "nanowatchrs"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
minijinja = { version = "2.3.1", features = ["loader"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
