name: Backend Check

on:
  # Allow manually triggering the workflow
  workflow_dispatch:
  schedule:
    # Every hour, on the hour
    - cron: "0 * * * *"

env:
  RUST_TOOLCHAIN: stable
  CHECK_NAME: Backend API

jobs:
  backend_check:
    name: Backend Status Check
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTOMATED_STATUS_CHECKS }}

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - run: |
          cargo run -- -c "${{ env.CHECK_NAME }}"
          git config --global user.name 'Isaac Donaldson'
          git config --global user.email 'isaacdonaldson@users.noreply.github.com'
          git add assets/ config/
          git commit -m "Update status for ${{ env.CHECK_NAME }}" && git push
